### PR TITLE
Update ja-jp.xaml

### PR DESCRIPTION
**Pull request by KobayshiMari**

### CODE REVIEW

**Comment by chiyi4488** [comment]
Hello?I am a translator in Traditional Chinese. What happened? Do you need me to pass the author of otp?

**Comment by KobayshiMari** [comment]
？？？

**Comment by chiyi4488** [comment]
>???

>en......

?????????

**Comment by KobayshiMari** [comment]
> > ???
> 
> > en......
> 
> ?????????

你说啥？？，我不太明白你在说啥，还有就是我不懂Github，如果你发现了什么问题就跟我说，恭请赐教

**Comment by chiyi4488** [comment]
沒事，我誤會了:D

**Pull request closed without merging**
